<?php

$data = [

	'team' => [

		[
			'id' => 'robert',
			'id2' => 'robert',
			'name' => 'Róbert',
			'title' => 'CEO',
			'icons' => [
				[ 'icon' => 'windows', 'title' => 'Windows' ],
				[ 'icon' => 'android', 'title' => 'Android' ],
				[ 'icon' => 'users', 'title' => 'ERP' ],
				[ 'icon' => 'photoshop', 'title' => 'Photoshop' ],
				[ 'icon' => 'camera-retro', 'title' => 'Fotózás' ],
				[ 'icon' => 'tree', 'title' => 'Természet' ],
				[ 'icon' => 'telescope', 'title' => 'Csillagászat' ],
				[ 'icon' => 'compass', 'title' => 'Túrázás' ],
				[ 'icon' => 'fighter-jet', 'title' => 'Modellezés' ],
			],
		],
		[
			'id' => 'neo21670',
			'id2' => 'marton',
			'name' => 'Márton',
			'title' => 'CTO',
			'icons' => [
				[ 'icon' => 'apple', 'title' => 'OS X / Apple / iOS' ],
				[ 'icon' => 'linux', 'title' => 'Linux' ],
				[ 'icon' => 'git', 'title' => 'Git' ],
				[ 'icon' => 'github4', 'title' => 'Github' ],
				[ 'icon' => 'twitter', 'title' => 'Twitter' ],
				[ 'icon' => 'server', 'title' => 'Üzemeltetés' ],
				[ 'icon' => 'archive', 'title' => 'Storage megoldások' ],
				[ 'icon' => 'bitcoin', 'title' => 'Bitcoin' ],
				[ 'icon' => 'desktop', 'title' => 'Mert a desktop fejlesztés még nem halott!' ],
				[ 'icon' => 'dashboard', 'title' => 'Gyorshajtás' ],
				[ 'icon' => 'train', 'title' => 'Transport Tycoon' ],
				[ 'icon' => 'film', 'title' => 'Sorozatok minden mennyiségben' ],
			],
		],
		[
			'id' => 'bence',
			'id2' => 'bence',
			'name' => 'Bence',
			'title' => 'Backend',
			'icons' => [
				[ 'icon' => 'debian', 'title' => 'Debian' ],
				[ 'icon' => 'java', 'title' => 'Java' ],
				[ 'icon' => 'android', 'title' => 'Android' ],
				[ 'icon' => 'gamepad', 'title' => 'Mass Effect' ],
				[ 'icon' => 'male', 'title' => 'Louie C.K.' ],
				[ 'icon' => 'rss', 'title' => 'TWiT' ],
				[ 'icon' => 'beer', 'title' => 'Legenda Sörfőzde' ],
				[ 'icon' => 'github4', 'title' => 'GitHub' ],
				[ 'icon' => 'stack-overflow', 'title' => 'StackOverflow' ],
				[ 'icon' => 'twitter', 'title' => 'Twitter' ],
				[ 'icon' => 'coffee', 'title' => 'Kávé' ],
				[ 'icon' => 'flask', 'title' => 'Tudományos módszer' ],
			],
		],
		[
			'id' => 'csy',
			'id2' => 'csaba',
			'name' => 'Csaba',
			'title' => 'Üzemeltetés',
			'icons' => [
				[ 'icon' => 'apple', 'title' => 'OS X / iOS' ],
				[ 'icon' => 'linux', 'title' => 'Debian / Ubuntu / CentOS / FreeNAS' ],
				[ 'icon' => 'server', 'title' => 'Vagrant' ],
				[ 'icon' => 'sitemap', 'title' => 'Varnish' ],
				[ 'icon' => 'meter', 'title' => 'Munin' ],
				[ 'icon' => 'coffee', 'title' => 'Kávé' ],
				[ 'icon' => 'film', 'title' => 'Game of Thrones' ],
				[ 'icon' => 'paw', 'title' => 'Kutyák' ],
				[ 'icon' => 'bullseye', 'title' => 'Paintball' ],
				[ 'icon' => 'sun', 'title' => 'Balaton' ],
				[ 'icon' => 'music', 'title' => 'Zene' ],
				[ 'icon' => 'twitter', 'title' => 'Twitter' ],
				[ 'icon' => 'gamepad', 'title' => 'Játék' ],
				[ 'icon' => 'beer', 'title' => 'Sör' ],
			],
		],
		[
			'id' => 'krisz',
			'id2' => 'krisztian',
			'name' => 'Krisztián',
			'title' => 'Üzleti elemzés',
			'icons' => [
				[ 'icon' => 'windows', 'title' => 'Windows' ],
				[ 'icon' => 'android', 'title' => 'Android' ],
				[ 'icon' => 'calculator', 'title' => 'Elemzés' ],
				[ 'icon' => 'money', 'title' => 'Pénzügyek' ],
				[ 'icon' => 'area-chart', 'title' => 'Statisztika' ],
				[ 'icon' => 'music', 'title' => 'Grunge' ],
				[ 'icon' => 'airplane', 'title' => 'Utazás' ],
				[ 'icon' => 'tree', 'title' => 'Természet' ],
				[ 'icon' => 'car', 'title' => 'Autók' ],
				[ 'icon' => 'weather-snow', 'title' => 'Jégkorong' ],
				[ 'icon' => 'bicycle', 'title' => 'Bringa' ],
			],
		],
		[
			'id' => 'lidi',
			'id2' => 'lidia',
			'name' => 'Lídia',
			'title' => 'Adminisztráció',
			'icons' => [
				[ 'icon' => 'windows', 'title' => 'Windows' ],
				[ 'icon' => 'android', 'title' => 'Android' ],
				[ 'icon' => 'archive', 'title' => 'Adminisztráció' ],
				[ 'icon' => 'coffee', 'title' => 'Kávé' ],
				[ 'icon' => 'film', 'title' => 'Filmek' ],
				[ 'icon' => 'gamepad', 'title' => 'Játék' ],
				[ 'icon' => 'run', 'title' => 'Zombies, Run!' ],
				[ 'icon' => 'music', 'title' => 'Zene' ],
				[ 'icon' => 'book', 'title' => 'Olvasás' ],
			],
		],
		[
			'id' => 'oszi',
			'id2' => 'oszkar',
			'name' => 'Oszkár',
			'title' => 'Backend',
			'icons' => [
				[ 'icon' => 'ubuntu', 'title' => 'Ubuntu' ],
				[ 'icon' => 'windows', 'title' => 'Windows' ],
				[ 'icon' => 'php', 'title' => 'PHP' ],
				[ 'icon' => 'laravel', 'title' => 'Laravel' ],
				[ 'icon' => 'mysql', 'title' => 'MySQL' ],
				[ 'icon' => 'pgsql', 'title' => 'PostgreSQL' ],
				[ 'icon' => 'html5', 'title' => 'HTML5' ],
				[ 'icon' => 'css3', 'title' => 'CSS3' ],
				[ 'icon' => 'rss', 'title' => 'Blogok olvasása' ],
				[ 'icon' => 'book', 'title' => 'Szakmai könyvek' ],
				[ 'icon' => 'reddit', 'title' => 'Reddit' ],
				[ 'icon' => 'stack-overflow', 'title' => 'StackOverflow' ],
				[ 'icon' => 'music', 'title' => 'Zene' ],
				[ 'icon' => 'youtube', 'title' => 'Youtube' ],
			],
		],
		[
			'id' => 'peti',
			'id2' => 'peter',
			'name' => 'Péter',
			'title' => 'Marketing',
			'icons' => [
				[ 'icon' => 'android', 'title' => 'Android' ],
				[ 'icon' => 'windows', 'title' => 'Windows' ],
				[ 'icon' => 'linux', 'title' => 'Linux' ],
				[ 'icon' => 'photoshop', 'title' => 'Photoshop' ],
				[ 'icon' => 'google', 'title' => 'Google Adwords' ],
				[ 'icon' => 'line-chart', 'title' => 'Google Analytics' ],
				[ 'icon' => 'shopping-cart', 'title' => 'Online marketing' ],
				[ 'icon' => 'facebook-square', 'title' => 'Közösségi média' ],
				[ 'icon' => 'css3', 'title' => 'CSS3' ],
				[ 'icon' => 'html5', 'title' => 'HTML5' ],
				[ 'icon' => 'coffee', 'title' => 'Kávé' ],
				[ 'icon' => 'music', 'title' => 'Zene' ],
				[ 'icon' => 'book', 'title' => 'George R. R. Martin: A tűz és jég dala' ],
				[ 'icon' => 'book', 'title' => 'Isaac Asimov: Robottörténetek' ],
			],
		],
		[
			'id' => 'kapa',
			'id2' => 'richard',
			'name' => 'Richárd',
			'title' => 'Frontend',
			'icons' => [
				[ 'icon' => 'debian', 'title' => 'Debian' ],
				[ 'icon' => 'windows', 'title' => 'Windows' ],
				[ 'icon' => 'android', 'title' => 'Android' ],
				[ 'icon' => 'css3', 'title' => 'CSS3' ],
				[ 'icon' => 'html5', 'title' => 'HTML5' ],
				[ 'icon' => 'javascript', 'title' => 'Javascript' ],
				[ 'icon' => 'coffee', 'title' => 'Kávé' ],
				[ 'icon' => 'angular', 'title' => 'AngularJS' ],
				[ 'icon' => 'stylus', 'title' => 'Stylus' ],
				[ 'icon' => 'stack-overflow', 'title' => 'StackOverflow' ],
				[ 'icon' => 'github4', 'title' => 'GitHub' ],
				[ 'icon' => 'sublime', 'title' => 'Sublime Text' ],
				[ 'icon' => 'futbol-o', 'title' => 'Foci' ],
				[ 'icon' => 'fish', 'title' => 'Akvarisztika' ],
			],
		],
		[
			'id' => 'br',
			'id2' => 'roland',
			'name' => 'Roland',
			'title' => 'Grafika',
			'icons' => [
				[ 'icon' => 'windows', 'title' => 'Windows' ],
				[ 'icon' => 'android', 'title' => 'Android' ],
				[ 'icon' => 'photoshop', 'title' => 'Photoshop' ],
				[ 'icon' => 'paint-brush', 'title' => 'Festés' ],
				[ 'icon' => 'pencil', 'title' => 'Rajzolás' ],
				[ 'icon' => 'compass', 'title' => 'Túrázás' ],
				[ 'icon' => 'history', 'title' => 'Történelem' ],
				[ 'icon' => 'bicycle', 'title' => 'Bringa' ],
			],
		],
		[
			'id' => 'default',
			'name' => '████',
			'title' => 'UX',
			'placeholder_days' => daysTillDate('2015/11/09'),
			'icons' => [
			],
		],
		[
			'id' => 'default',
			'name' => '████',
			'title' => 'Sitebuild',
			'placeholder_days' => daysTillDate('2015/11/05'),
			'icons' => [
			],
		],
		[
			'id' => 'default',
			'name' => '█████',
			'title' => 'Backend',
			'placeholder_days' => daysTillDate('2015/12/07'),
			'icons' => [
			],
		],
		[
			'id' => 'default',
			'name' => '████',
			'title' => 'Backend',
			'placeholder_days' => daysTillDate('2015/11/02'),
			'icons' => [
			],
		],

	]

];

function daysTillDate($date) {
	$cdate = strtotime($date);
	$difference = $cdate - time();
	if ($difference < 0) $difference = 0;
	return floor($difference / 60 / 60 / 24);
}

?>

